[package]
name = "arc"
version = "0.1.0"
authors = ["Anicet Ebou <anicet.ebou@gmail.com>"]
edition = "2021"
description = "arc is a fast archive converter"
homepage = "https://github.com/Ebedthan/arc"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["archive converter"]

[dependencies]
anyhow = "1"
clap = { version = "4.6", features = ["derive"] }
clap_complete = "4.5"
which = "7"


[profile.release]
opt-level = 3
debug = true
overflow-checks = false
lto = 'thin'
panic = 'abort'
incremental = false

[[bin]]
name = "arc"
path = "src/main.rs"
bench = false
